   version: '3'

   services:
     db:
       image: mysql:5.7
       container_name: practice_mysql
       environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: practice_mysql
         MYSQL_USER: mysql_user
         MYSQL_PASSWORD: password
       volumes:
       - ./docker/db/data:/var/lib/mysql
       - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
       restart: always
       ports:
       - 3306:3306